<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodeVisualisierung.CSharp.Contract</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NJsonSchema" />
    <None Include="../../../../contracts/graph-universe/schema/graph-universe.schema.json" Link="graph-universe.schema.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>
</Project>
