<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodeVisualisierung.CSharp.Analysis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeVisualisierung.CSharp.Contract/CodeVisualisierung.CSharp.Contract.csproj" />
    <ProjectReference Include="../CodeVisualisierung.CSharp.Graph/CodeVisualisierung.CSharp.Graph.csproj" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
  </ItemGroup>
</Project>
